# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: rachel levanger
email: rachel.levanger@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Rachel spends her time in New York City, where she nurtures her passions for
  mathematics, painting, cooking, birding, and rock climbing.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://rachellevanger.com" # the base hostname & protocol for your site
twitter_username: RachelLevanger
github_username: rachellevanger
linkedin_username: rachel-levanger-5a6b395

# Build settings
markdown: kramdown

